export {default as cat1} from "../../assets/cat1.png"
export {default as cat2} from "../../assets/cat2.png"
export {default as cat3} from "../../assets/cat3.png"
export {default as cat4} from "../../assets/cat4.png"
export {default as cat5} from "../../assets/cat5.png"
export {default as Article3} from "../../assets/Article3.jpg"
export {default as Article4} from "../../assets/Article4.jpg"
export {default as Article5} from "../../assets/Article5.jpg"
export {default as Article6} from "../../assets/Article6.jpg"
export {default as Article1} from "../../assets/Article1.jpg"
export {default as Article2} from "../../assets/Article2.jpg"
export {default as vegi} from "../../assets/Link → cat-4.png.png"